---
version: "3.7"
services:
  jamulus:
    container_name: jamulus 
    image: jamulus:HEAD
    build: .
    restart: always
    ports:
      - "${PORT}:${PORT}/udp"
    environment:
      TZ: "America/New_York"  
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--port"
      - "${PORT}"
      - "--welcomemessage"
      - "Rob Richards - ${HOSTNAME}"
      - "--numchannels"
      - "4"
