---
version: "3.7"
services:
  jamulus:
    container_name: jamulus-docker 
    image: jamulus-server:HEAD
    build:
      context: ./
      args:
        - JAMULUS_RELEASE=r3_5_8
    restart: always
    ports:
      - "22124:22124/udp"
    environment:
      TZ: "America/New_York"  
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--port"
      - "22124"
      - "--welcomemessage"
      - "Jamulus Server"
      - "--numchannels"
      - "4"
